### ISSUE TITLE
How to run multiple jobs at same time?

### ISSUE THREAD

**Issue by Ammadkhalid** [morlandi/django-task#3]
* Django Task version: 1.4.3
* Django version: 2.2.3
* Python version: 3.7.4
* Operating System: Unix (Ubuntu, Mac)

### Description
There is anyway i can run more than one job at same time? whenever i tried to execute more than one job at same. It waits for active to task complete and set itself `Pending`.

Do i have to run multiple workers ? if yes there is anyway to `autoscale` them?

Thank you.

**Comment by morlandi** [comment]
Hello @Ammadkhalid ,
sorry for late response, somehow I missed your interesting issue.

Keeping new jobs pending in the queue while a previous one is still in progress is **the very one reason** for using a task queue.
The main benefits are scalability and predictability: despite how many tasks will be created at run-time, you limit and plan in advance the resources devoted to those tasks.

Sometimes, another benefit is that you might need to serialize the tasks: they might contend a shared resource, for example a serial connection. In that case, you should lock the shared resource, or ... **much simpler** ... let the task scheduler serialize all tasks for you.

In case you need or find convenient to parallelize some activities, the solution, as you correctly suggested, is to run multiple workers to serve the same queue.

In development, just run more worker instances with: `python manage.py rqworker QUEUENAME`.
For example, with three running workers, you should see something like this:

<img width="1011" alt="Screenshot 2019-11-07 05 20 25" src="https://user-images.githubusercontent.com/299854/68359985-701fcb80-011e-11ea-8468-9073396cb670.png">

Try experimenting with that: you can even start more workers while some jobs are already pending in the queue, and the new workers will start immediately to consume messages.

In production, I normally use supervisor to schedule the workers; in the following example, I'm using three workers for the "high" queue, and one for the "low" queue.
You can even use a single worker to serve multiple queues: just list the queues to work on, separated by space, in the "rqworker" command (I never had a real need for that, however).

    [program:myproject_rqworker_high]
    directory=/home/myproject/myproject
    command=/home/myproject/python/bin/python manage.py rqworker --worker-ttl=120 myproject_high
    user=myproject
    group=myproject
    autostart=true
    autorestart=true
    numprocs=3
    process_name=%(process_num)01d
    stdout_logfile=/home/myproject/logs/rqworker_high_%(process_num)01d.log
    stderr_logfile=/home/myproject/logs/rqworker_high_%(process_num)01d.log

    [program:myproject_rqworker_low]
    directory=/home/myproject/myproject
    command=/home/myproject/python/bin/python manage.py rqworker --worker-ttl=120 myproject_low
    user=myproject
    group=myproject
    autostart=true
    autorestart=true
    numprocs=1
    process_name=%(process_num)01d
    stdout_logfile=/home/myproject/logs/rqworker_low_%(process_num)01d.log
    stderr_logfile=/home/myproject/logs/rqworker_low_%(process_num)01d.log

**Comment by Ammadkhalid** [comment]
Thank you so much for great explanation!, i'll give this a try!
