### ISSUE TITLE
Try to implement 'example'

### ISSUE THREAD

**Issue by zN3utr4l** [morlandi/django-task#5]
* Django Task version: latest
* Django version: 3.0.7
* Python version: 3.7.8
* Operating System: WIN 10

### Description

I tried to implement your 'example' in my project, but every new job I create or goes to me in REJECTED mode while if I run the command python manage.py rqworker example_default it returns me PENDING but I can't execute it

![Cattura](https://user-images.githubusercontent.com/73225008/98693197-4b34e880-2370-11eb-8614-f3ed14bf40cc.PNG)
![Cattura](https://user-images.githubusercontent.com/73225008/98693524-b1217000-2370-11eb-8f74-07d5cdfcedfe.jpg)

PS C:\Users\g.chirico\Desktop\Git\honeypot> python manage.py rqworker example_default
RQ_QUEUES: 
{'example_default': {'URL': 'redis://localhost:6379/0', 'DEFAULT_TIMEOUT': -1}, 'example_low': {'URL': 'redis://localhost:6379/0'}, 'example_high': {'URL': 'redis://localhost:6379/0', 'DEFAULT_TIMEOUT': 500}}
16:08:49 Worker rq:worker:4ea840be12a64e7ebc2665d7684fb39f: started, version 1.6.1
16:08:49 Subscribing to channel rq:pubsub:4ea840be12a64e7ebc2665d7684fb39f
16:08:49 *** Listening on example_default...
16:08:49 Cleaning registries for queue: example_default
16:09:10 example_default: run(task_class=<class 'variables.models.CountBeansTask'>, task_id=UUID('f678c47d-28c5-4d9c-9776-7fb75fd0f682')) (6ddb36c4-ce92-4eac-95e0-d00069fa77b3)
16:09:10 Worker rq:worker:4ea840be12a64e7ebc2665d7684fb39f: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\rq\worker.py", line 579, in work
    self.execute_job(job, queue)
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\rq\worker.py", line 811, in execute_job
    self.fork_work_horse(job, queue)
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\rq\worker.py", line 729, in fork_work_horse
    child_pid = os.fork()
AttributeError: module 'os' has no attribute 'fork'
16:09:10 Unsubscribing from channel rq:pubsub:4ea840be12a64e7ebc2665d7684fb39f

**Comment by zN3utr4l** [comment]
**When i try to click on run on the REJECTED tasks this is the result**

TypeError at /admin/variables/countbeanstask/1a4a0981-2900-4e7a-9ab8-def65da6c03b/run/
run() got multiple values for argument 'object_id'

Environment:
Request Method: GET
Request URL: http://127.0.0.1:8000/admin/variables/countbeanstask/1a4a0981-2900-4e7a-9ab8-def65da6c03b/run/

Django Version: 3.0.7
Python Version: 3.7.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'hellow',
 'countryCharts',
 'variables',
 'django_task',
 'django_rq']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\g.chirico\AppData\Local\Programs\Python\Python37\lib\site-packages\django\contrib\admin\sites.py", line 231, in inner
    return view(request, *args, **kwargs)

Exception Type: TypeError at /admin/variables/countbeanstask/1a4a0981-2900-4e7a-9ab8-def65da6c03b/run/
Exception Value: run() got multiple values for argument 'object_id'

**Comment by morlandi** [comment]
Hello @zN3utr4l ,
as far as I know, rq doesn't work on Windows.
In your traceback, the command "python manage.py rqworker ...", supplied by django-rq, fails due to the lack of os.fork().
As a consequence, no worker is running, and from the main command "python manage.py runserver" django-task complains about this.

There is PR for the rq project to fix this:
https://github.com/rq/rq/pull/860
but it's still pending and rather old.

Also, you might want to take a look at this option:
https://github.com/michaelbrooks/rq-win

I do not normally use Windows in my projects; however, I'ld be interested in hearing about any progress on this ;)

**Comment by zN3utr4l** [comment]
ok so, you dont know how i can schedule tasks on my django project? I Need docker i think

**Comment by morlandi** [comment]
Docker doesn't help here.
You should either try https://github.com/michaelbrooks/rq-win with rq, or switch to Celery.

For django-task, I opted to use rq, which is simpler, since based on Redis alone, while Celery can be used with several brokers.
If you know in advance you will use Redis (that is my case), Celery is a little bit over-engineered to my taste.
However, Celery might work on Windows - although not officially supported

**Comment by zN3utr4l** [comment]
Yes, I think I want to use redis as a broker, but could you get me curious? Redis works only as a repository for a job queue or has other uses, from what I have found on the internet little is understood.

However if Windows does not support fork () I think that no type of job scheduler works on it, apart from a "schedule" which, however, needs a While TRUE to work: and I don't understand how it is possible to define it as a scheduler. (I'm Italian too)

**Comment by morlandi** [comment]
Redis is, basically, an in-memory data structure store.
You can think of it as a super-fast database which keeps data in RAM for super-fast access.
This can be used in a number of ways, for example as a message broker (as you already now) or for caching frequently consulted information (much like memcache).
It also provides support for real-time communications, being a PUB/SUB server; if you're interested, and since you're italian, you might want to take a look at the talk I gave on this subject at PyCon Italy 2019: https://www.youtube.com/watch?v=xxbxVHi_vfU

On Windows, I do believe https://github.com/michaelbrooks/rq-win provides a workaround to use rq despite os.fork() not being available

**Comment by zN3utr4l** [comment]
Really thanks for the help and explanation, I'll see the video, it looks very interesting, but moving on, on https://github.com/michaelbrooks/rq-win the worker is given without any explanation or implementation and for me, new in this area (django / job scheduler) I don't understand where that script goes, I asked a question about their repository, I hope they answer me.

**Comment by morlandi** [comment]
> I asked a question about their repository

Well done. Let me know if you get any useful feedback on this.
I'm glad I switched from Celery to Rq, but regret I lost the possibility to support background tasks on Windows ... sooner or later I might need to fix this.

**Comment by zN3utr4l** [comment]
Thanks for the help, so you confirm that django rq works great on UX systems and consequently if I were to undertake a scheduling project on django I could very well use this your 'django-task' module?

**Comment by morlandi** [comment]
Yes, I've been using django-task in production for a few years in several projects deployed on Ubuntu, and use it for development on Mac with no problems. Occasionally, I add some small improvements here and there as the specific project requires.

Up to now, the only nuisance has been the need to upgrade a few external dependencies from time to time, tipically when Ubuntu switches to a new version of Redis:

- redis (thas is, pyredis)
- rq
- django-rq

and, in case:
- django-redis-cache

When you deploy the very same project on different servers, each with it's own version of Redis installed, it's not always obvious how to pin each python package, and same trial and error might be required.

However, upgrades where even more troublesome with Celery, as far as I remember.

**Comment by zN3utr4l** [comment]
I understand, however I wanted to inform you that I just managed to schedule jobs on windows thanks to django-apscheduler that is a Django application, and it runs on all platforms that are officially supported by the Django project.

**Comment by morlandi** [comment]
Nice to know; that's interesting, and I will certainly take a look at it.
As far as I understood after a quick look at the readme, you are limited to start the backup jobs from code (for example with management command), then django-apscheduler provides a view to monitor it's progress from the web in the admin.
This sometimes is not enough. The purpose of django-task is twofold:
- either monitor the progress of background jobs (and collected logs) via web
- or, start new jobs interactively from the admin
I opted to have one derived model for each Task "type" precisely for the purpose of having a specific form (kindly provided by Django) suitable to collect the required parameters to start a new job.

**Comment by zN3utr4l** [comment]
Yes, you say well, if I wanted to create a job or a task from the / admin route it is not possible because, when you go to run it always through / admin, an error such as, job not found, comes out, so I assume that that management command goes to instantiate that job somewhere that I did not understand and mostly if I go to execute a job created with that management command from the admin panel, it does not execute it n times as many times as it was registered in the schedule.add_job block but only once.

**Comment by zN3utr4l** [comment]
Sorry, would you take away a curiosity? For example, I have a graph, then a series of values, and 2 variables or thresholds, i.e. max and min and I want to check that the values ​​do not exceed this threshold and if these thresholds are exceeded I am notified, but there is a hitch, the min and max ranges are editable by the user, now comes the question. Already instantiated jobs can't change their arguments right? That is, I would like that this control work on the variables is always and continuously done and that django precisely goes to schedule this job. I think it cannot be done, I think that at the "Modification of values" event django must initialize and instantiate a new job by modifying the management command and re-executing it, however this would lead to a waste of time that could be even millisendes I think but anyway a loss. As I said, I am new and I say these after various tests and various unsuccessful research, you, certainly more informed and more experienced than me, would you be able to tell me if there is a solution or some other django module capable of doing this?
Really thanks in advance.

**Comment by leonardo-albertovich** [comment]
> 
> 
> Redis is, basically, an in-memory data structure store.
> You can think of it as a super-fast database which keeps data in RAM for super-fast access.
> This can be used in a number of ways, for example as a message broker (as you already now) or for caching frequently consulted information (much like memcache).
> It also provides support for real-time communications, being a PUB/SUB server; if you're interested, and since you're italian, you might want to take a look at the talk I gave on this subject at PyCon Italy 2019: https://www.youtube.com/watch?v=xxbxVHi_vfU
> 
> On Windows, I do believe https://github.com/michaelbrooks/rq-win provides a workaround to use rq despite os.fork() not being available

First of all sorry to interrupt but I wanted to shed some light on the topic as it might help someone interested on it.

The thing with rq-win is that it runs the task code in the same process and that's when the lack of features to implement a watchdog make things messy and not production level. That's the reason why I chose to deal with spawning child processes and also the reason why I tried to use WSASetBlockingHook (which doesn't work well on newer windows versions).

My fork is seriously outdated since it's three years old but it worked as a drop in replacement so if I was in a position where I needed to be able to use it on windows I'd give it a try or at least diff the changed files and patch the latest version, the changes were self contained so I seriously doubt it would be a difficult thing to do.

Regards.

**Comment by morlandi** [comment]
Great stuff @leonardo-albertovich ... I regret that https://github.com/rq/rq/pull/860 didn't bring to a shared solution.
Unfortunately, I'm not currently working on Windows, so I don't foresee any chance to work with it in the near future. 
Thank you for sharing your efforts.

**Comment by morlandi** [comment]
@zN3utr4l for your specific need, you should use some form of interprocess communication between the main process and the background job; one simple way would be to share some variable via Redis, and read them periodically from the background job loop, to detect any updated value

**Comment by zN3utr4l** [comment]
So that every time a new variable is found I go to create a new job, I can't reuse the old ones right?

**Comment by morlandi** [comment]
not at all, your job is already running ... keep it running, and just make it responsive to "shared variables" values changes.
Wasn't this your purpose?

**Comment by zN3utr4l** [comment]
Yes, let me explain, I have a motor that I have to monitor and through a PLC I read n variables such as power, etc., and I have to check these variables every time the PLC sends me variables, to archive them I use the UPC-UA protocol and the I put either on a Postgresql DB or InfluxDB from which I should read all the time.

**Comment by zN3utr4l** [comment]
However, the rq-win module you recommended works, that is, it no longer gives forking problems, but the SendEmailJob does nothing, maybe it's me who didn't understand how it works, could you explain it to me?

**Comment by zN3utr4l** [comment]
Implementing this module on docker, the error on the fork no longer occurs but when I go to run a job that previously failed, I get this error:

![Cattura](https://user-images.githubusercontent.com/73225008/99531548-31fcef00-29a3-11eb-874e-529b05dff110.PNG)

Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/tasks/countbeanstask/2cda55d6-bafc-4329-a88c-fad9b7e5a416/run/

Django Version: 3.1.3
Python Version: 3.9.0
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_rq',
 'django_task',
 'example',
 'tasks']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)

Exception Type: TypeError at /admin/tasks/countbeanstask/2cda55d6-bafc-4329-a88c-fad9b7e5a416/run/
Exception Value: run() got multiple values for argument 'object_id'

**Comment by morlandi** [comment]
@zN3utr4l , I regret I can't discuss here application-specific issues.
django-task has been used successfully in several Django project, so rest be assured it does work.
I'm going to close this issue now
